### PR TITLE
Fix compilation errors and pom

### PR DESCRIPTION
**Pull request by kiview**
Updates compilation errors and fixes dependencies in Maven POM.

How was ist even working before?

### CODE REVIEW

**Comment by kiview** [comment]
Oh sorry, I am not sure why he sees the whole file as diff, this probably comes from Unix style line breaks.

**Comment by kgiannis** [comment]
Yes, probably. I was working on a Windows machine for that project.

**Comment by kiview** [comment]
Should I do a new PR, without changed line breaks?

**Comment by kgiannis** [comment]
The last update I did in .pom, I remember was due to security updates in Jackson. I will test it again. But you are right, this used to work (It's been long since I used it, there is version 2.0 of Multichain out now). I will merge your PR

**Comment by kiview** [comment]
Do you have or use a similar Java client for version 2.0?

**Comment by kgiannis** [comment]
Unfortunately, no. I wanted to create a new one and write an article about it but didn't have the time. Streams with JSON support is a powerful concept.

**Pull request merged**
